
trigger:
  - main

pool:
  name: myagent

stages:
  - stage: BuildStage
    jobs:
      - job: buildjob
        displayName: Build Job
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '6'
          - task: Npm@1
            inputs:
              command: 'install'
              workingDir: '$(System.DefaultWorkingDirectory)/azure%20pipeline/elearn-frontend'
          - task: Npm@1
            inputs:
              command: 'custom'
              workingDir: '$(System.DefaultWorkingDirectory)/azure%20pipeline/elearn-frontend'

              customCommand: 'run build'
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/azure%20pipeline/elearn-frontend/build'
              ArtifactName: 'myartifact'
              publishLocation: 'Container'
  - stage: deploystage
    dependsOn: BuildStage
    displayName: Deply
    jobs:
      - job: deploystage
        displayName: Deploy Stage
        steps:

        - task: DownloadPipelineArtifact@2
          inputs:
            buildType: 'current'
            artifactName: 'myartifact'
            targetPath: '$(Build.StagingDirectory)'

        - task: SSH@0
          inputs:
            sshEndpoint: 'vmconnection'
            runOptions: 'commands'
            commands: |
              sudo chmod -R 777 /var/www/html
              sudo rm -rf /var/www/html/*
            readyTimeout: '20000'
        - task: CopyFilesOverSSH@0
          inputs:
            sshEndpoint: 'vmconnection'
            sourceFolder: '$(Build.StagingDirectory)/myartifact'
            contents: '**'
            targetFolder: '/var/www/html'
            readyTimeout: '20000'
