
pool: self -agent

trigger:
- main

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/resourc'
    backendServiceArm: 'connection service'
    backendAzureRmResourceGroupName: 'skdmp'
    backendAzureRmStorageAccountName: 'skdmpstg'
    backendAzureRmContainerName: 'azcontainer'
    backendAzureRmKey: 'tf/terraform.tfstate'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'